language: rust
os: linux
dist: bionic
addons:
  apt:
    packages: [libpcap0.8, libpcap0.8-dev]
jobs:
  include:
    - {os: linux, rust: stable,
       env: FLAGS="--features capture-stream"}
    - {os: linux, rust: beta,
       env: FLAGS="--features capture-stream"}
    - {os: osx, rust: stable,
       env: FLAGS="--features full" PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
    - {os: osx, rust: beta,
       env: FLAGS="--features full" PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
before_install:
- |-
    case $TRAVIS_OS_NAME in
      osx)
        brew update >/dev/null;
        brew install libpcap;
        ;;
    esac
before_script:
  - rustup component add clippy
script:
  - cargo build -v $FLAGS
  - cargo test  -v $FLAGS
  - cargo clippy
  - cargo doc --no-deps
