os:
  - linux
  - osx
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - libpcap-dev
before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then
      brew update >/dev/null;
      brew install libpcap;
    fi
script:
  - FEATURES=tokio,pcap-fopen-offline-precision;
  - if [ "$TRAVIS_OS_NAME" = osx ]; then
      FEATURES=full;
      export PCAP_LIBDIR=$(brew --prefix libpcap)/lib;
    fi
  - if [ "$TRAVIS_RUST_VERSION" = nightly ]; then
      FEATURES+=,clippy;
    fi
  - cargo test --features "$FEATURES"
  - cargo doc  --features "$FEATURES" --no-deps
