[package]

name = "pcap"
version = "0.6.1"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "A packet capture API around pcap/wpcap"
keywords = ["pcap", "packet", "sniffing"]
readme = "README.md"
homepage = "https://github.com/ebfull/pcap"
repository = "https://github.com/ebfull/pcap"
documentation = "https://docs.rs/pcap"
license = "MIT OR Apache-2.0"
build = "build.rs"

[dependencies]
libc = "0.2"
clippy = { version = "0.0.134", optional = true }
futures = "*"
mio = "*"
tokio-core = "*"

[dev-dependencies]
tempdir = "0.3"

[features]
# This feature enables access to the function Capture::savefile_append.
# This is disabled by default, because it depends on a relatively recent
# version of libpcap (1.7.2).
pcap-savefile-append = []

# This feature enables access to the function Capture::from_raw_fd_with_precision.
# This is disabled by default, because it requires libpcap >= 1.5.0.
pcap-fopen-offline-precision = []

# A shortcut to enable all features.
full = ["pcap-savefile-append", "pcap-fopen-offline-precision"]

[lib]
name = "pcap"

[[example]]
name = "listenlocalhost"
path = "examples/listenlocalhost.rs"

[[example]]
name = "getdevices"
path = "examples/getdevices.rs"

[[example]]
name = "easylisten"
path = "examples/easylisten.rs"

[[example]]
name = "savefile"
path = "examples/savefile.rs"

[[example]]
name = "getstatistics"
path = "examples/getstatistics.rs"

[[example]]
name = "non_block"
path = "examples/non_block.rs"
